my:
  name: forezp
  age: 12
bean:
  name: martin
  age: 12
  number: ${random.int}
  uuid:  ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${bean.name}
spring:
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/SpringBoot
       username: root
       password: start123
